#
# --.--                        ,---,o          |              
#   |  ,---.,-.-.,-.-.,   .     .-' .,---.,---.|    ,---.,---.
#   |  |   || | || | ||   |    |    ||---'|   ||    |---'|    
#   `  `---'` ' '` ' '`---|    `---'``---'`---|`---'`---'`    
#                     `---'               `---'               
# 

# Metadata
title: Tommy Ziegler
email: me@tommyziegler.com
description: >
  Hier schreiben Mitarbeiter von OPITZ CONSULTING zu Technologien, Werkzeugen,
  Methoden und anderen interessanten Erkenntnissen und Erlebnissen aus ihrem
  Arbeitsalltag bei und für unsere Kunden.

# URL
baseurl: ""
url: "http://tommyziegler.github.io"

# Social Media Links
twitter_username: tommyziegler_de
github_username: tommyziegler
youtube_username: TommyZiegler

# Google Analytics
google_analytics_code:

# Markdown
markdown: kramdown

# Permanent Links
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
gems: [jekyll-paginate]
paginate_path: "/pages/:num/"

# Collections
collections:
  authors:
    output: true
    permalink: /authors/:path/
  topics:
    output: true
    permalink: /categories/:path/

# Layout Defaults
defaults:
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Ascii Text generated with http://www.network-science.de/ascii (Font: big)
